baseurl = "http://krukas.dyn.amicdns.de/~pi/blueprint/"
languageCode = "de-de"
title = "Blueprint"
theme="blueprint"

[Params]
  description = "we work for change"


[[menu.main]]
    name = "Profile"
    url = "/profile"
    weight = -170


