baseurl = "http://krukas.dyn.amicdns.de/"
languageCode = "de-de"
title = "blueprint"
subtitle = "wir helfen Produktentwicklung zu skalieren"

[Params]
  themeColor = "theme-base-0d"
  description = "wir helfen, ihre Produktentwicklung zu skalieren"


[[menu.main]]
    name = "Charta"
    pre = "<i class='fa fa-download'></i>"
    url = "/charta/"
    weight = -200
[[menu.main]]
    name = "Produkt"
    url = "/product/"
    weight = -180
[[menu.main]]
    name = "Profile"
    url = "/profiles/"
    weight = -170
[[menu.main]]
    name = "Erfahrung"
    url = "/erfahrung/"
    weight = -160
[[menu.main]]
    name = "Impressum"
    url = "/impressum/"
    weight = -150



