baseurl = "http://krukas.dyn.amicdns.de/~pi/blueprint/"
languageCode = "de-de"
title = "blueprint"
subtitle = "wir helfen Produktentwicklung zu skalieren"
theme="blueprint"

[Params]
  description = "wir helfen, ihre Produktentwicklung zu skalieren"


[[menu.main]]
    name = "Profile"
    url = "/profiles/"
    weight = -170


