baseurl = "http://krukas.dyn.amicdns.de/~pi/blueprint/"
languageCode = "de-de"
title = "Blueprint"
theme="blueprint"

[Params]
  description = "we work for change"
  cite = "Jeff Bezos: \"Am gefährlichsten ist es, sich nicht zu verändern\""

[[menu.main]]
    name = "Profile"
    url = "/profile"
    weight = -150


